In [1]:
import torch

In [2]:
class rnn(torch.nn.Module):

    def __init__(self):
        super(rnn, self).__init__()

        self.ih = torch.nn.Linear(64, 128)
        self.hh = torch.nn.Linear(128, 128)

    def rnnCell(self, input, hidden):
        """
        TODO: Using only the above defined linear layers and a tanh
              activation, create an Elman RNN cell.  You do not need
              to include an output layer.  The network should take
              some input (inputDim = 64) and the current hidden state
              (hiddenDim = 128), and return the new hidden state.
        """
        return torch.tanh(self.ih(input) + self.hh(hidden))

    def forward(self, input):
        hidden = torch.zeros(128)
        """
        TODO: Using self.rnnCell, create a model that takes as input
              a sequence of size [seqLength, batchSize, inputDim]
              and passes each input through the rnn sequentially,
              updating the (initally zero) hidden state.
              Return the final hidden state after the
              last input in the sequence has been processed.
        """
        for seq in input:
            hidden = self.rnnCell(seq, hidden)
        return hidden

In [3]:
class rnnSimplified(torch.nn.Module):

    def __init__(self):
        super(rnnSimplified, self).__init__()
        """
        TODO: Define self.net using a single PyTorch module such that
              the network defined by this class is equivalent to the
              one defined in class "rnn".
        """
        self.net = torch.nn.RNN(64,128)

    def forward(self, input):
        hidden = torch.zeros(1,1,128)
        _, hidden = self.net(input, hidden)
        return hidden

In [4]:
def lstm(input, hiddenSize):
    """
    TODO: Let variable lstm be an instance of torch.nn.LSTM.
          Variable input is of size [batchSize, seqLength, inputDim]
    """
    lstm = torch.nn.LSTM(input.shape[2],hiddenSize, batch_first=True)
    return lstm(input)

def conv(input, weight):
    """
    TODO: Return the convolution of input and weight tensors,
          where input contains sequential data.
          The convolution should be along the sequence axis.
          input is of size [batchSize, inputDim, seqLength]
    """
    return torch.nn.functional.conv1d(input.shape[0], weight)

# 测试神经网络是否正确

### rnn

In [202]:
x = torch.rand(20, 64)
y = torch.ones(128)

net = rnn()
optimizer = torch.optim.Adam(net.parameters(), lr = 1e-4)
loss_func = torch.nn.MSELoss()

In [212]:
for e in range(30):
    _loss = 0
    for i,data in enumerate(x):
        output = net(x)
        loss = loss_func(y, output)
        loss.backward()
        optimizer.step()
        _loss += loss.item()
    if e % 5 == 0:
        print(_loss)
print(output)

1.957676483144155e-07
8.174656773718425e-08
3.5554505894985766e-08
1.5948500353690775e-08
7.314123751100965e-09
3.4046740149396015e-09
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 0.9999, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1

In [213]:
with torch.no_grad():
    pred = net(torch.rand(1,64))
    cost = 1 - pred
    print(pred)
    print(cost.sum())

tensor([0.8167, 1.0000, 0.9774, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 0.9829, 0.9990, 0.9771, 0.6492, 0.9615, 1.0000,
        0.9202, 1.0000, 1.0000, 0.9698, 1.0000, 1.0000, 1.0000, 0.8850, 1.0000,
        1.0000, 0.3096, 0.9613, 0.9999, 0.9942, 0.9986, 0.9999, 1.0000, 0.9991,
        1.0000, 1.0000, 1.0000, 1.0000, 0.9991, 0.9943, 1.0000, 1.0000, 0.9948,
        1.0000, 0.9206, 0.9999, 1.0000, 1.0000, 1.0000, 0.9999, 0.9998, 0.9991,
        1.0000, 0.9621, 1.0000, 1.0000, 1.0000, 0.9803, 0.9968, 1.0000, 0.9582,
        0.9990, 1.0000, 1.0000, 1.0000, 1.0000, 0.9900, 0.9996, 1.0000, 0.9901,
        0.8392, 0.9924, 1.0000, 0.8318, 1.0000, 0.9999, 0.9900, 0.9960, 0.9761,
        1.0000, 0.7626, 0.9985, 0.9999, 1.0000, 1.0000, 0.5686, 0.9971, 0.9999,
        0.9999, 0.9999, 1.0000, 0.9999, 0.9269, 1.0000, 0.9733, 1.0000, 1.0000,
        1.0000, 0.9785, 1.0000, 1.0000, 1.0000, 0.6117, 0.9876, 0.7154, 0.9999,
        1.0000, 0.9794, 1.0000, 1.0000, 

### rnnSimplified

In [214]:
x = torch.rand(20, 64)
y = torch.ones(128)

net = rnnSimplified()

#### net.fit()

In [215]:
 for e in range(30):
    _loss = 0
    for i, data in enumerate(x):
        output = net(data.view(1,1,-1))
        loss = loss_func(y, output)
        loss.backward()
        optimizer.step()
        _loss += loss.item()
    if e % 5 == 0:
        print(_loss)
print(output)

19.63486647605896
6.97745606303215
1.6615901067852974
0.35867406334728
0.0789528206223622
0.01815788417297881
tensor([[[0.9935, 0.9830, 0.9854, 0.9886, 0.9867, 0.9779, 0.9927, 0.9928,
          0.9802, 0.9732, 0.9849, 0.9816, 0.9810, 0.9562, 0.9862, 0.9938,
          0.9927, 0.9885, 0.9873, 0.9823, 0.9755, 0.9814, 0.9710, 0.9853,
          0.9884, 0.9872, 0.9877, 0.9827, 0.9914, 0.9849, 0.9874, 0.9745,
          0.9846, 0.9796, 0.9936, 0.9877, 0.9856, 0.9924, 0.9896, 0.9811,
          0.9869, 0.9881, 0.9891, 0.9795, 0.9865, 0.9880, 0.9877, 0.9878,
          0.9934, 0.9753, 0.9805, 0.9907, 0.9902, 0.9886, 0.9806, 0.9850,
          0.9916, 0.9872, 0.9936, 0.9892, 0.9412, 0.9907, 0.9742, 0.9780,
          0.9880, 0.9807, 0.9846, 0.9878, 0.9918, 0.9831, 0.9874, 0.9845,
          0.9870, 0.9775, 0.9842, 0.9784, 0.9908, 0.9868, 0.9884, 0.9799,
          0.9878, 0.9903, 0.9853, 0.9833, 0.9875, 0.9820, 0.9746, 0.9665,
          0.9846, 0.9776, 0.9915, 0.9906, 0.9794, 0.9600, 0.9821, 0.9850,
  

In [216]:
# Predict
with torch.no_grad():
    pred = net(torch.rand(1,1,64))
    cost = 1 - pred
    print(pred)
    print(cost.sum())

tensor([[[0.9906, 0.9893, 0.9841, 0.9903, 0.9893, 0.9857, 0.9954, 0.9908,
          0.9849, 0.9787, 0.9916, 0.9840, 0.9914, 0.9793, 0.9902, 0.9937,
          0.9924, 0.9848, 0.9926, 0.9863, 0.9796, 0.9826, 0.9860, 0.9878,
          0.9909, 0.9854, 0.9882, 0.9871, 0.9933, 0.9927, 0.9896, 0.9920,
          0.9914, 0.9855, 0.9953, 0.9904, 0.9891, 0.9909, 0.9917, 0.9832,
          0.9920, 0.9901, 0.9882, 0.9806, 0.9891, 0.9922, 0.9786, 0.9865,
          0.9926, 0.9796, 0.9904, 0.9939, 0.9960, 0.9911, 0.9877, 0.9930,
          0.9934, 0.9940, 0.9959, 0.9928, 0.9795, 0.9791, 0.9817, 0.9856,
          0.9925, 0.9867, 0.9843, 0.9915, 0.9911, 0.9929, 0.9881, 0.9835,
          0.9919, 0.9924, 0.9932, 0.9871, 0.9870, 0.9904, 0.9876, 0.9845,
          0.9900, 0.9909, 0.9874, 0.9867, 0.9891, 0.9867, 0.9815, 0.9799,
          0.9902, 0.9891, 0.9951, 0.9917, 0.9857, 0.9839, 0.9835, 0.9915,
          0.9904, 0.9916, 0.9909, 0.9740, 0.9921, 0.9908, 0.9943, 0.9881,
          0.9867, 0.9857, 0.9932, 0.98

### lstm

In [18]:
x = torch.rand(10, 20, 64)
_lstm = lstm(x, 64, )
print(_lstm[1][0].shape)

torch.Size([1, 10, 64])
